config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions:'users/sessions', shared:'users/shared' }

  resources :products

  get '/cart', to:'cart#index'
  get '/cart/clear', to:'cart#clearCart'

  get '/cart/:id/quantity/:quantity', to:'cart#add', as:'add_to_cart'

  get '/cart/remove/:id', to:'cart#remove'

  root 'page#home'

  get 'page/about'

  get 'page/faqs'

  get 'page/contact'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ":style/missing_avatar.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

    validates_attachment_presence :avatar
    validates_attachment_content_type :avatar, :content_type => ["image/jpeg", "image/gif", "image/png"]
    validates_attachment_size :avatar, :less_than => 5.megabytes

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:show, :index]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:tiltle, :description, :avatar, :price, :date, :time, :stock)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">

  <div class="row">
   <div class="col-xs-12-offset-3" id ="wrapper_1">

<%= form_for @product, html: {:multipart => true} do |f| %>


<!-- PACKAGE FORM STARTS HERE -->
<div class="panel panel-default credit-card-box" id="form-body">
    <div class="panel-heading display-table" id="PanelTitulo">
        <div class="row display-tr" >
            <h3 class="panel-title display-td" >Detalles del Paquete</h3>
            <div class="display-td" >
                  <img class="img-responsive pull-right" id="user-avatar" src="/img/Infonica.png">
            </div>
        </div>
    </div>

<!-- Date Picker 3 -->
<!--
 <div class="span5 col-md-5" id="sandbox-container">
<label>Fecha y Hora</label>
//rails f.text_field :date, readonly: true
 </div>
 -->

 <div class="row">
     <div class="col-xs-12">
         <div class="form-group">
             <label for="couponCode">Fecha y Hora del Paquete</label>

             <div class="form-inline">
               <div class="form-group">
                 <div class="input-group">
                 <%= f.text_field :date, id:"date", class:"form-control"%>
                 <div class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></div>
                </div>
              </div>

              <div class="form-group">
                <div class="input-group">
              <%= f.text_field :time, id:"time", class:"form-control"%>
                <div class="input-group-addon"><span class="glyphicon glyphicon-time"></span></div>
              </div>
             </div>

             </div>

         </div>
     </div>
 </div>



<!-- DateTimePicker -->

<!--

<div style="overflow:hidden;">
  <div class="form-group">
          <div class="col-md-8">
              <div id="datetimepicker"></div>
          </div>
  </div>

  <div id="timepicker"></div>

-->

<!-- image_tag @product.avatar.url
image_tag @product.avatar.url(:thumb)


-->


<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <label for="couponCode">Fotografia del Paquete</label>

            <%=  image_tag @product.avatar.url(:medium), class:"img-thumbnail", id:"Product_img" %>

            <div class="row">
            <%= f.file_field :avatar, id:"Select_Product_img", class:"btn btn-primary" %>
            </div>

        </div>
    </div>
</div>


<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <label for="couponCode">Nombre del Paquete</label>

            <%= f.text_field :tiltle, class:"form-control",
            placeholder:"Paquete #", required: true %>

        </div>
    </div>
</div>


<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <label for="couponCode">Descripcion del paquete</label>

          <%= f.text_area :description, class:"form-control",
          placeholder:"Incluye...", required: true, rows:"8" %>

        </div>
    </div>
</div>


<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <label for="couponCode">Precio del Paquete</label>

    <%= f.number_field :price ,min:1, step: 1, value:100, class:"form-control", required: true%>

        </div>
    </div>
</div>


<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <label for="couponCode">No. de Cupos del Paquete</label>

    <%= f.number_field :stock ,min:1, step: 1, value:1, class:"form-control", required: true%>

        </div>
    </div>
</div>

</div>

  <div class="actions">
    <%= f.submit 'Guardar', class:"btn btn-success btn-lg btn-block"  %>
  </div>
<% end %>



</div>
</div>
</div>

<script>

$(function () {

			$('#date').bootstrapMaterialDatePicker
			({
        lang : 'es',
        format : 'DD/MM/YYYY',
        time: false,
        minDate : new Date()
        //format : 'dddd, DD MMMM YYYY - hh:mm A',
			});

      $('#time').bootstrapMaterialDatePicker
      ({
          lang : 'es',
          format : 'hh:mm A',
          date: false
      });

/*

$('#datetimepicker').datetimepicker({
    format: 'DD/MM/YYYY - hh:mm A',
    defaultDate: moment("12/02/2015 - 08:40 AM", "DD/MM/YYYY - hh:mm A"),
    inline: true,
    sideBySide: true,
    locale: 'es',
    minDate: moment("12/02/2015 - 08:40 AM", "DD/MM/YYYY - hh:mm A"),         //set a minimum date  <---- HERE
    maxDate: moment("12/02/2015 - 08:40 AM", "DD/MM/YYYY - hh:mm A")

});

      $('#timepicker').datetimepicker({
        format: 'hh:mm A',
        defaultDate: moment("08:25 AM", "hh:mm A"),
        inline: true,
        sideBySide: true,
        locale: 'es',
        minDate: moment("08:25 AM", "hh:mm A"),         //set a minimum date  <---- HERE
        maxDate: moment("08:25 AM", "hh:mm A")

      });
*/



      /*
      DATE PICKER 3
      $('#sandbox-container input').datepicker({
          format: "dd-MM-yyyy",
          language: "es",
          autoclose: true,
          todayHighlight: true
      });
      */

    });


    function handleFileSelect(evt) {
        var files = evt.target.files; // FileList object
          f=files[0]
          // Only process image files.
          if (f.type.match('image.*')) {
            var reader = new FileReader();
            reader.onload = (function(theFile) {
              return function(e) {
                // alert(e.target.result);
                document.getElementById("Product_img").src=e.target.result;
              };
            })(f);

          // Read in the image file as a data URL.
          reader.readAsDataURL(f);
          }
        }
      document.getElementById('Select_Product_img').addEventListener('change', handleFileSelect, false);


</script>

app/views/products/edit.html.erb
<div class="page-header">
  <h1>Editar Paquete</h1>
</div>


<%= render 'form' %>

<%= link_to '<i class="glyphicon glyphicon-arrow-left"></i> Regresar'.html_safe, products_path, class:"btn btn-info", style:"margin-left: 35px; margin-top:20px;" %>
<%= link_to '<i class="glyphicon glyphicon-modal-window"></i> Mostrar'.html_safe, @product, class:"btn btn-warning", style:"margin-left: 35px; margin-top:20px;" %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="new_Product">
  <div class="page-header">
    <h1>Paquetes turisticos</h1>
  </div>
<%= link_to '<i class="glyphicon glyphicon-plus"></i> Nuevo producto'.html_safe, new_product_path, class:"btn btn-xs btn-primary" %>
</div>

  <tbody>

    <% @products.each do |product| %>

      <div class="col-sm-4 col-lg-4 col-md-4" id="wrapper_product">
        <div class="thumbnail" id="product-conteiner">
          	<%=  image_tag product.avatar.url(), class: "img-responsive thumbnail"  %>
             <div class="caption">
               <h4 class="pull-right"><%= number_to_currency(product.price, unit: '$') %></h4>
              <h4><%= link_to product.tiltle, product %></h4>
              <p id="description"><%= product.description %></p>
            </div>


<div id="btn-opciones">

            <div class="ratings">
              <p class="pull-right">
                <% if product.stock > 0 %>
                <span class="label label-success"> <%= product.stock %> CUPOS</span>
                <% else %>
                <span class="label label-danger"> AGOTADA</span>
                <% end %>

              </p>

                          <div class="form-group">
                            <label class="control-label text-uppercase" for="input-quantity">Cantidad:</label>
                            <input type="number" name="quantity" value="1" size="2" min="1" step="1" max="<%= product.stock %>" id="quantity-input_<%=product.id%>" class="form-control" />
                          </div>

              <p>
              <span>
              <%= link_to '<i class="glyphicon glyphicon-pencil"></i> Editar'.html_safe,
              edit_product_path(product), class:"btn btn-xs btn-success"%>
              </span>
              <span><%= link_to '<i class="glyphicon glyphicon-remove"></i> Eliminar'.html_safe,
              product, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-xs btn-danger" %></span>
              <span>
                <a class="btn btn-xs btn-primary" href="#" onclick="cart(<%=product.id%>)" id="link_cart_<%=product.id%>"><i class="glyphicon glyphicon-shopping-cart"></i> Agregar a Carrito</a>


            <!-- link_to('<i class="glyphicon glyphicon-shopping-cart"></i> Agregar a Carrito'.html_safe,
             add_to_cart_path(product.id, 8), class:"btn btn-xs btn-primary") -->
              </span>
              </p>
            </div>

          </div>

          </div>
        </div>


    <% end %>


  </tbody>

  <script type="text/javascript">

        $(document).ready(function() {

            <% @products.each do |product| %>
          // para number input, solo aceptar numero y teclas especiales
        $("#quantity-input_<%=product.id%>").keydown(function (e) {

                // Allow: backspace, delete, tab, escape, enter and .
                if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                     // Allow: Ctrl+A
                    (e.keyCode == 65 && e.ctrlKey === true) ||
                     // Allow: Ctrl+C
                    (e.keyCode == 67 && e.ctrlKey === true) ||
                     // Allow: Ctrl+X
                    (e.keyCode == 88 && e.ctrlKey === true) ||
                     // Allow: home, end, left, right
                    (e.keyCode >= 35 && e.keyCode <= 39)) {
                         // let it happen, don't do anything
                         return;
                }
                // Ensure that it is a number and stop the keypress
                if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                    e.preventDefault();
                }

            });
        // para input number convertir a entero
        $("#quantity-input_<%=product.id%>").blur(function (e) {

              if($(this).val() == ""){
              $(this).val(1);
              }
              else{
                if($(this).val()<1){
                $(this).val(1);
                }
                else{
                  var num = $(this).val();
                  var num_f = parseInt(num);
                  $(this).val(num_f);
                }

              }
                });

        <% end %>

                });

          function cart(x){

                    var id = x;
                    var cantidad = document.getElementById("quantity-input_"+id).value;

                  //  alert("cantidad "+cantidad+"id "+id);
                    document.getElementById("link_cart_"+id).href="cart/"+id+"/quantity/"+cantidad;
                    return false;
                  }

  </script>






<br>

app/views/products/new.html.erb
<div class="page-header">
  <h1>Nuevo Paquete</h1>
</div>


<%= render 'form' %>

<%= link_to '<i class="glyphicon glyphicon-arrow-left"></i> Regresar'.html_safe, products_path, class:"btn btn-info", style:"margin-left: 35px; margin-top:20px;" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<!-- Product Info Starts -->
					<div class="row product-info">
					<!-- Left Starts -->
						<div class="col-sm-5 images-block">
							<p>
								<%=  image_tag @product.avatar.url(), class: "img-responsive thumbnail"  %>
							</p>
							<p>
								<%=  image_tag @product.avatar.url(), class: "img-responsive thumbnail"  %>
							</p>
							<!--
							<ul class="list-unstyled list-inline">
								<li>
									<%=  image_tag @product.avatar.url(:thumb), class: "img-responsive thumbnail"  %>
								</li>
								<li>
									<%=  image_tag @product.avatar.url(:thumb), class: "img-responsive thumbnail"  %>
								</li>
								<li>
									<%=  image_tag @product.avatar.url(:thumb), class: "img-responsive thumbnail"  %>
								</li>

							</ul>
						-->
						</div>
					<!-- Left Ends -->
					<!-- Right Starts -->
						<div class="col-sm-7 product-details" id="product-details">
						<!-- Product Name Starts -->
							<h2><%= @product.tiltle %></h2>
						<!-- Product Name Ends -->
							<hr/>
						<!-- Manufacturer Starts -->
							<ul class="list-unstyled manufacturer">

                 <li>
									<span>Disponibilidad: </span>
									<% if @product.stock > 0 %>
									<strong class="label label-success"> <%= @product.stock %> CUPOS</strong>
									<% else %>
									<strong class="label label-danger"> AGOTADA</strong>
									<% end %>
								 </li>
							</ul>
						<!-- Manufacturer Ends -->

						<div style="overflow:hidden;">
						  <div class="form-group">
						          <div class="col-md-8">
						              <div id="datetimepicker"></div>
						          </div>
						  </div>
						</div>

							<script>

							$(function () {

								$('#datetimepicker').datetimepicker({
										format: 'DD/MM/YYYY - hh:mm A',
										defaultDate: moment("<%= @product.date %> - <%= @product.time %>", "DD/MM/YYYY - hh:mm A"),
										inline: true,
										sideBySide: true,
										locale: 'es',
										minDate:  moment("<%= @product.date %> - <%= @product.time %>", "DD/MM/YYYY - hh:mm A"),        //set a minimum date  <---- HERE
										maxDate:  moment("<%= @product.date %> - <%= @product.time %>", "DD/MM/YYYY - hh:mm A")

								});

							});

								</script>


						<!-- Fecha -->
	<!--
						<div class="container">
						    <div class="row">
						        <div class='col-sm-6'>
						            <div class="form-group">
						                <div class='input-group date' id='datetimepicker'>
						                    <input type='text' class="form-control"/>
						                    <span class="input-group-addon">
						                        <span class="glyphicon glyphicon-calendar"></span>
						                    </span>
						                </div>
						            </div>
						        </div>
						        <script type="text/javascript">
						            $(function () {
						                $('#datetimepicker').datetimepicker({
						                locale: 'es',
														format: 'dddd, MMMM DD YYYY, h:mm:ss a',
 														format:'DD.MM.YYYY',
													//	useCurrent: false,
													//	disable: true,
														minDate: Date.now()

						                });

											//  $('#datetimepicker').data("DateTimePicker").Date('11/11/2015');
						            });


						        </script>
						    </div>
						</div>

						 -->

							<hr />
						<!-- Price Starts -->
							<div class="price">
								<span class="price-head">Precio :</span>
								<span class="price-new"><%= number_to_currency(@product.price, unit: '$') %></span>
							</div>
						<!-- Price Ends -->
							<hr />
						<!-- Available Options Starts -->
							<div class="options">
								<div class="form-group">
									<label class="control-label text-uppercase" for="input-quantity">Cantidad:</label>

									<input type="number" name="quantity" value="1" size="2" min="1" step="1" max="<%= @product.stock %>"
									id="quantity-input" class="form-control" />
								</div>
								<div class="cart-button button-group">
									<span>
									<a class="btn btn-xs btn-primary" href="#" onclick="cart(<%=@product.id%>)" id="link_cart">
										<i class="glyphicon glyphicon-shopping-cart"></i> Agregar a Carrito</a>
									</span>
							<!--
								<a href="/cart/<%= @product.id %>" class="btn btn-xs btn-primary">Agregar a carrito</a>
									<button type="button" class="btn btn-cart">
										Agregar a carrito
										<i class="fa fa-shopping-cart"></i>
									</button> -->
								</div>
							</div>
						<!-- Available Options Ends -->
							<hr />
						</div>
					<!-- Right Ends -->
					</div>
				<!-- product Info Ends -->
				<!-- Product Description Starts -->
				<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Descripcion</h3>
  </div>
  <div class="panel-body">
	<%= @product.description %>
  </div>
</div>

<script type="text/javascript">

			$(document).ready(function() {

				// para number input, solo aceptar numero y teclas especiales
			$("#quantity-input").keydown(function (e) {

							// Allow: backspace, delete, tab, escape, enter and .
							if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
									 // Allow: Ctrl+A
									(e.keyCode == 65 && e.ctrlKey === true) ||
									 // Allow: Ctrl+C
									(e.keyCode == 67 && e.ctrlKey === true) ||
									 // Allow: Ctrl+X
									(e.keyCode == 88 && e.ctrlKey === true) ||
									 // Allow: home, end, left, right
									(e.keyCode >= 35 && e.keyCode <= 39)) {
											 // let it happen, don't do anything
											 return;
							}
							// Ensure that it is a number and stop the keypress
							if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
									e.preventDefault();
							}

					});
			// para input number convertir a entero
			$("#quantity-input").blur(function (e) {

						if($(this).val() == ""){
						$(this).val(1);
						}
						else{
							if($(this).val()<1){
							$(this).val(1);
							}
							else{
								var num = $(this).val();
								var num_f = parseInt(num);
								$(this).val(num_f);
							}

						}
							});


							});

				function cart(x){

									var id = x;
									var cantidad = document.getElementById("quantity-input").value;

								//  alert("cantidad "+cantidad+"id "+id);
									document.getElementById("link_cart").href="/cart/"+id+"/quantity/"+cantidad;
									return false;
								}

</script>
				<!-- Product Description Ends -->

<%= link_to 'Editar', edit_product_path(@product), class:"btn btn-xs btn-warning" %> |
<%= link_to 'Regresar', products_path, class:"btn btn-xs btn-info" %>